
aws:
  cognito:
    region: us-east-1
    userPoolId:
    cognitoClientId :
    jwkSetUri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}
    accessKey:
    secretKey:

spring:
  application:
    name: spring-security-aws
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}
