
aws:
  cognito:
    region: us-east-1
    userPoolId: us-east-1_examplepoolid
    cognitoClientId : <here is the client id>
    jwkSetUri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json

spring:
  application:
    name: spring-security-aws
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}
